### ISSUE TITLE
Should call http_shutdown() upon receiving a termination signal (TERM, INT)

### ISSUE THREAD

**Issue by dualbus** [maxburke/oneshot#3]
Need to call shutdown() on the socket to free it, otherwise the OS will keep the socket open in the TIME-WAIT state:

    dualbus@debian:~/local/src/maxburke/oneshot$ ./oneshot
    oneshot[8632]: 127.0.0.1 - [2017-03-10:22:16:51] "GET / HTTP/1.1" 301 98
    ^C
    dualbus@debian:~/local/src/maxburke/oneshot$ ./oneshot
    oneshot[8633]: Unable to bind listening socket to local port 8080 (errno: 98)
    dualbus@debian:~/local/src/maxburke/oneshot$ ss -nat|grep 8080
    TIME-WAIT  0      0      127.0.0.1:8080               127.0.0.1:56872

**Comment by maxburke** [comment]
Calling shutdown() when receiving SIGINT/SIGTERM shuts the main listen socket down, but not the children. If the children call shutdown() on fork(), the socket is closed even for the parent, preventing future accept() calls.

I've set the accept socket to use SO_REUSEADDR which allows the program to immediately restart once terminated.

Any objections to this approach?

**Comment by dualbus** [comment]
You're right, SO_REUSEADDR seems like the way to go.

Although I do have a slight confusion. After reading https://hea-www.harvard.edu/~fine/Tech/addrinuse.html, it looks like the socket is left in the TIME-WAIT state because it's oneshot the one that initiates the tear down of the connection by sending FIN ("Local end initiates closure"), instead of letting the client tear it down.

Running oneshot under strace:

    dualbus@debian:~/local/src/maxburke/oneshot$ strace -ttfe trace=network,file ./oneshot
    09:02:20.036018 execve("./oneshot", ["./oneshot"], [/* 33 vars */]) = 0
    09:02:20.036671 access("/etc/ld.so.nohwcap", F_OK) = -1 ENOENT (No such file or directory)
    09:02:20.036799 access("/etc/ld.so.preload", R_OK) = -1 ENOENT (No such file or directory)
    09:02:20.036886 open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
    09:02:20.037059 access("/etc/ld.so.nohwcap", F_OK) = -1 ENOENT (No such file or directory)
    09:02:20.037135 open("/usr/lib/x86_64-linux-gnu/libsodium.so.18", O_RDONLY|O_CLOEXEC) = 3
    09:02:20.037396 access("/etc/ld.so.nohwcap", F_OK) = -1 ENOENT (No such file or directory)
    09:02:20.037456 open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
    09:02:20.037769 access("/etc/ld.so.nohwcap", F_OK) = -1 ENOENT (No such file or directory)
    09:02:20.037834 open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
    09:02:20.038861 socket(AF_UNIX, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 3
    09:02:20.038931 connect(3, {sa_family=AF_UNIX, sun_path="/dev/log"}, 110) = 0
    09:02:20.039063 mkdir("data/", 0700)    = -1 EEXIST (File exists)
    09:02:20.039130 stat("data/", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
    09:02:20.039195 chmod("data/", 0700)    = 0
    09:02:20.039408 socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 4
    09:02:20.039475 bind(4, {sa_family=AF_INET, sin_port=htons(8080), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
    09:02:20.039541 listen(4, 16)           = 0
    09:02:20.039593 accept(4, {sa_family=AF_INET, sin_port=htons(57538), sin_addr=inet_addr("127.0.0.1")}, [128->16]) = 5
    strace: Process 10541 attached
    [pid 10539] 09:02:23.549245 accept(4,  <unfinished ...>
    [pid 10541] 09:02:23.550148 open("/usr/share/zoneinfo/America/Mexico_City", O_RDONLY|O_CLOEXEC) = 4
    oneshot[10541]: 127.0.0.1 - [2017-03-11:09:02:23] "GET / HTTP/1.1" 301 98
    [pid 10541] 09:02:23.550502 sendto(3, "<30>Mar 11 09:02:23 oneshot[1054"..., 93, MSG_NOSIGNAL, NULL, 0) = 93
    [pid 10541] 09:02:23.550628 shutdown(5, SHUT_WR) = 0
    [pid 10541] 09:02:23.552753 +++ exited with 0 +++
    09:02:23.552778 <... accept resumed> 0x7ffead9f19c0, [128]) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
    09:02:23.552805 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=10541, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
    09:02:23.552832 accept(4, 0x7ffead9f19c0, [128]) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
    09:02:28.284983 --- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=10542, si_uid=1000} ---
    09:02:28.285202 +++ killed by SIGTERM +++
    dualbus@debian:~/local/src/maxburke/oneshot$ ss -nat|grep 8080
    TIME-WAIT  0      0      127.0.0.1:8080               127.0.0.1:57538              

Request sent by curl:

    dualbus@debian:~/local/src/maxburke/oneshot$ curl http://127.0.0.1:8080/ -v
    *   Trying 127.0.0.1...
    * TCP_NODELAY set
    * Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
    > GET / HTTP/1.1
    > Host: 127.0.0.1:8080
    > User-Agent: curl/7.52.1
    > Accept: */*
    > 
    < HTTP/1.1 301 Moved Permanently
    < Location: /static/
    < Content-Type: text/html
    < Connection: close
    < 
    * Curl_http_done: called premature == 0
    * Closing connection 0
    dualbus@debian:~/local/src/maxburke/oneshot$ pkill oneshot

TCP trace (it shows the FIN is sent by oneshot, then the FIN-ACK by curl):

    dualbus@debian:~/local/src/maxburke/oneshot$ sudo tcpdump -n 'port 8080' -i lo
    tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
    listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes
    09:02:23.548166 IP 127.0.0.1.57538 > 127.0.0.1.8080: Flags [S], seq 1762045026, win 43690, options [mss 65495,sackOK,TS val 11476240 ecr 0,nop,wscale 7], length 0
    09:02:23.548204 IP 127.0.0.1.8080 > 127.0.0.1.57538: Flags [S.], seq 3006660222, ack 1762045027, win 43690, options [mss 65495,sackOK,TS val 11476240 ecr 11476240,nop,wscale 7], length 0
    09:02:23.548232 IP 127.0.0.1.57538 > 127.0.0.1.8080: Flags [.], ack 1, win 342, options [nop,nop,TS val 11476240 ecr 11476240], length 0
    09:02:23.548362 IP 127.0.0.1.57538 > 127.0.0.1.8080: Flags [P.], seq 1:79, ack 1, win 342, options [nop,nop,TS val 11476240 ecr 11476240], length 78: HTTP: GET / HTTP/1.1
    09:02:23.548376 IP 127.0.0.1.8080 > 127.0.0.1.57538: Flags [.], ack 79, win 342, options [nop,nop,TS val 11476240 ecr 11476240], length 0
    09:02:23.549783 IP 127.0.0.1.8080 > 127.0.0.1.57538: Flags [P.], seq 1:99, ack 79, win 342, options [nop,nop,TS val 11476240 ecr 11476240], length 98: HTTP: HTTP/1.1 301 Moved Permanently
    09:02:23.549799 IP 127.0.0.1.57538 > 127.0.0.1.8080: Flags [.], ack 99, win 342, options [nop,nop,TS val 11476240 ecr 11476240], length 0
    09:02:23.550674 IP 127.0.0.1.8080 > 127.0.0.1.57538: Flags [F.], seq 99, ack 79, win 342, options [nop,nop,TS val 11476241 ecr 11476240], length 0
    09:02:23.550859 IP 127.0.0.1.57538 > 127.0.0.1.8080: Flags [F.], seq 79, ack 100, win 342, options [nop,nop,TS val 11476241 ecr 11476241], length 0
    09:02:23.550878 IP 127.0.0.1.8080 > 127.0.0.1.57538: Flags [.], ack 80, win 342, options [nop,nop,TS val 11476241 ecr 11476241], length 0
    ^C
    10 packets captured
    20 packets received by filter
    0 packets dropped by kernel

Whereas doing the same for google:

    dualbus@debian:~/local/src/maxburke/oneshot$ curl http://google.com:80 -v
    * Rebuilt URL to: http://google.com:80/
    *   Trying 64.233.168.138...
    * TCP_NODELAY set
    * Connected to google.com (64.233.168.138) port 80 (#0)
    > GET / HTTP/1.1
    > Host: google.com
    > User-Agent: curl/7.52.1
    > Accept: */*
    > 
    < HTTP/1.1 302 Found
    < Cache-Control: private
    < Content-Type: text/html; charset=UTF-8
    < Location: http://www.google.com.mx/?gfe_rd=cr&ei=xhPEWNymFIfirAb9vJqwAQ
    < Content-Length: 262
    < Date: Sat, 11 Mar 2017 15:12:06 GMT
    < 
    <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
    <TITLE>302 Moved</TITLE></HEAD><BODY>
    <H1>302 Moved</H1>
    The document has moved
    <A HREF="http://www.google.com.mx/?gfe_rd=cr&amp;ei=xhPEWNymFIfirAb9vJqwAQ">here</A>.
    </BODY></HTML>
    * Curl_http_done: called premature == 0
    * Connection #0 to host google.com left intact

TCP trace shows that in this case it's curl who actually sends the first FIN:

    dualbus@debian:~/local/src/maxburke/oneshot$ sudo tcpdump -n  'port 80' 
    tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
    listening on wlo1, link-type EN10MB (Ethernet), capture size 262144 bytes
    09:12:06.153737 IP 192.168.0.4.45450 > 64.233.168.138.80: Flags [S], seq 2527337832, win 29200, options [mss 1460,sackOK,TS val 11621891 ecr 0,nop,wscale 7], length 0
    09:12:06.268518 IP 64.233.168.138.80 > 192.168.0.4.45450: Flags [S.], seq 2570796080, ack 2527337833, win 42408, options [mss 1380,sackOK,TS val 3137143429 ecr 11621891,nop,wscale 7], length 0
    09:12:06.268596 IP 192.168.0.4.45450 > 64.233.168.138.80: Flags [.], ack 1, win 229, options [nop,nop,TS val 11621920 ecr 3137143429], length 0
    09:12:06.268714 IP 192.168.0.4.45450 > 64.233.168.138.80: Flags [P.], seq 1:75, ack 1, win 229, options [nop,nop,TS val 11621920 ecr 3137143429], length 74: HTTP: GET / HTTP/1.1
    09:12:06.456568 IP 64.233.168.138.80 > 192.168.0.4.45450: Flags [.], ack 75, win 332, options [nop,nop,TS val 3137143529 ecr 11621920], length 0
    09:12:06.464320 IP 64.233.168.138.80 > 192.168.0.4.45450: Flags [P.], seq 1:480, ack 75, win 332, options [nop,nop,TS val 3137143530 ecr 11621920], length 479: HTTP: HTTP/1.1 302 Found
    09:12:06.464355 IP 192.168.0.4.45450 > 64.233.168.138.80: Flags [.], ack 480, win 237, options [nop,nop,TS val 11621969 ecr 3137143530], length 0
    09:12:06.464682 IP 192.168.0.4.45450 > 64.233.168.138.80: Flags [F.], seq 75, ack 480, win 237, options [nop,nop,TS val 11621969 ecr 3137143530], length 0
    09:12:06.549460 IP 64.233.168.138.80 > 192.168.0.4.45450: Flags [F.], seq 480, ack 76, win 332, options [nop,nop,TS val 3137143710 ecr 11621969], length 0
    09:12:06.549509 IP 192.168.0.4.45450 > 64.233.168.138.80: Flags [.], ack 481, win 237, options [nop,nop,TS val 11621990 ecr 3137143710], length 0
    ^C
    10 packets captured
    10 packets received by filter
    0 packets dropped by kernel

That's the limit of my knowledge though, so I don't know how to change oneshot to not send the first FIN. From what I can tell, main.c:client_shutdown_connection seems to do the right thing.

**Comment by maxburke** [comment]
The oneshot http server sends the "Connection: close" header to the client to inform it that the server will be closing the connection once the request has been processed. This is because I didn't want to handle persistent connections.

I did notice that the Google page doesn't send the same header.

If I add -H "Connection: close" when I curl Google I see both the "Connection: close" header in the response as well as Google initiating the FIN:

`max@homer:~$ curl -H "Connection: close" http://google.com:80 -v
* Rebuilt URL to: http://google.com:80/
*   Trying 172.217.3.174...
* Connected to google.com (172.217.3.174) port 80 (#0)
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.50.1
> Accept: */*
> Connection: close
> 
< HTTP/1.1 302 Found
< Cache-Control: private
< Content-Type: text/html; charset=UTF-8
< Location: http://www.google.ca/?gfe_rd=cr&ei=82DEWKDFMsbe8AfD7bsQ
< Content-Length: 256
< Date: Sat, 11 Mar 2017 20:41:23 GMT
< Connection: close
< 
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.ca/?gfe_rd=cr&amp;ei=82DEWKDFMsbe8AfD7bsQ">here</A>.
</BODY></HTML>
* Closing connection 0
`

`max@homer:~$ sudo tcpdump -n  'port 80' 
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eno1, link-type EN10MB (Ethernet), capture size 262144 bytes
12:41:23.803534 IP 192.168.0.10.46162 > 172.217.3.174.80: Flags [S], seq 47949619, win 29200, options [mss 1460,sackOK,TS val 97987848 ecr 0,nop,wscale 7], length 0
12:41:23.820992 IP 172.217.3.174.80 > 192.168.0.10.46162: Flags [S.], seq 1414530882, ack 47949620, win 42408, options [mss 1380,sackOK,TS val 2998721825 ecr 97987848,nop,wscale 7], length 0
12:41:23.821036 IP 192.168.0.10.46162 > 172.217.3.174.80: Flags [.], ack 1, win 229, options [nop,nop,TS val 97987853 ecr 2998721825], length 0
12:41:23.821121 IP 192.168.0.10.46162 > 172.217.3.174.80: Flags [P.], seq 1:94, ack 1, win 229, options [nop,nop,TS val 97987853 ecr 2998721825], length 93: HTTP: GET / HTTP/1.1
12:41:23.836966 IP 172.217.3.174.80 > 192.168.0.10.46162: Flags [.], ack 94, win 332, options [nop,nop,TS val 2998721841 ecr 97987853], length 0
12:41:23.837649 IP 172.217.3.174.80 > 192.168.0.10.46162: Flags [P.], seq 1:487, ack 94, win 332, options [nop,nop,TS val 2998721841 ecr 97987853], length 486: HTTP: HTTP/1.1 302 Found
12:41:23.837669 IP 192.168.0.10.46162 > 172.217.3.174.80: Flags [.], ack 487, win 237, options [nop,nop,TS val 97987857 ecr 2998721841], length 0
12:41:23.837802 IP 172.217.3.174.80 > 192.168.0.10.46162: Flags [F.], seq 487, ack 94, win 332, options [nop,nop,TS val 2998721841 ecr 97987853], length 0
12:41:23.837819 IP 192.168.0.10.46162 > 172.217.3.174.80: Flags [F.], seq 94, ack 487, win 237, options [nop,nop,TS val 97987857 ecr 2998721841], length 0
12:41:23.837830 IP 192.168.0.10.46162 > 172.217.3.174.80: Flags [.], ack 488, win 237, options [nop,nop,TS val 97987857 ecr 2998721841], length 0
12:41:23.861096 IP 172.217.3.174.80 > 192.168.0.10.46162: Flags [.], ack 95, win 332, options [nop,nop,TS val 2998721861 ecr 97987857], length 0
^C
11 packets captured
11 packets received by filter
0 packets dropped by kernel
max@homer:~$ 
`

**Comment by maxburke** [comment]
Any other thoughts on this? Would you mind if I closed it?

**Comment by dualbus** [comment]
Yes, I think this can be closed since the main issue (being unable to launch oneshot due to the TIME-WAIT socket) is already fixed.

Thanks!
